name: Release Binaries

on: [push, pull_request]

jobs:
    build:
      runs-on: ubuntu-latest
      name: build
      steps:
        - uses: actions/checkout@v2
        - name: Setup go
          uses: actions/setup-go@v2
          with:
            go-version: 1.16.5
        - run: make build
    release-bin:
      runs-on: ubuntu-latest
      name: release
      steps:
        - uses: actions/checkout@v2
        - name: Setup go
          uses: actions/setup-go@v2
          with:
            go-version: 1.16.5
        - name: build windows amd64
          run: GOOS=windows GOARCH=amd64 EXECUTABLE=go_sync_win_x64.exe make build-go
        - name: build windows i386
          run: GOOS=windows GOARCH=386 EXECUTABLE=go_sync_win.exe make build-go
        - name: build linux amd64
          run: GOOS=linux GOARCH=amd64 EXECUTABLE=go_sync_linux_x64 make build-go
        - name: build linux i386
          run: GOOS=linux GOARCH=386 EXECUTABLE=go_sync_linux make build-go
        - name: build linux arm
          run: GOOS=linux GOARCH=arm EXECUTABLE=go_sync_linux_arm make build-go
        - name: build linux arm64
          run: GOOS=linux GOARCH=arm64 EXECUTABLE=go_sync_linux_arm64 make build-go
        - name: build mac amd64
          run: GOOS=darwin GOARCH=amd64 EXECUTABLE=go_sync_macos_amd64 make build-go
        - name: build mac arm64
          run: GOOS=darwin GOARCH=arm64 EXECUTABLE=go_sync_macos_arm64 make build-go
        - name: Archive production artifacts Windows amd64
          uses: actions/upload-artifact@v2
          with:
            name: windows-amd64
            path: go_sync_win_x64.exe
        - name: Archive production artifacts Windows i386
          uses: actions/upload-artifact@v2
          with:
            name: windows-i386
            path: go_sync_win.exe
        - name: Archive production artifacts Linux amd64
          uses: actions/upload-artifact@v2
          with:
            name: linux-amd64
            path: go_sync_linux_x64
        - name: Archive production artifacts Linux i386
          uses: actions/upload-artifact@v2
          with:
            name: linux-i386
            path: go_sync_linux
        - name: Archive production artifacts Linux arm
          uses: actions/upload-artifact@v2
          with:
            name: linux-arm
            path: go_sync_linux_arm
        - name: Archive production artifacts Linux arm64
          uses: actions/upload-artifact@v2
          with:
            name: linux-arm64
            path: go_sync_linux_arm64
        - name: Archive production artifacts Mac amd64
          uses: actions/upload-artifact@v2
          with:
            name: mac-amd64
            path: go_sync_macos_amd64
        - name: Archive production artifacts Mac arm64
          uses: actions/upload-artifact@v2
          with:
            name: mac-arm64
            path: go_sync_macos_arm64